title: Trustworthy LM

show_excerpts: true
sass:
  sass_dir: _sass

permalink: /posts/:title/

texture:
  title: AIS631005 Trustworthy LM
  style: black
  showNav: true
  showPicker: false

  social_links:
    github:  thelehhman

plugins:
  - jekyll-seo-tag
  - jekyll-feed
