title: Trustworthy LM
author: GitHub User
email: your-email@domain.com

show_excerpts: false
sass:
  sass_dir: _sass

permalink: /posts/:title/

texture:
  title: AIS631005 Trustworthy LM
  tagline: FDU.FVL.Xingjun MA
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false

  social_links:
    github:  thelehhman
 
header_pages:
  - about.md


plugins:
  - jekyll-seo-tag
#  - jekyll-feed
