title: Trustworthy LM

show_excerpts: true
sass:
  sass_dir: _sass

permalink: /posts/:title/

texture:
  title: AIS631005 Trustworthy LM
  style: black
  showNav: true
  showPicker: false

  social_links:
    github:  xingjunm
    google:  https://scholar.google.com.au/citations?user=XQViiyYAAAAJ&hl=en
    e-mail:  http://xingjunma.com/

plugins:
  - jekyll-seo-tag
  - jekyll-feed
